### ISSUE TITLE
Directory Missing for Plotting: logs/figure6b

### ISSUE THREAD

**Issue by kingzevin** [pkusys/ElasticFlow#1]
I really appreciate your fabulous work.
I'm trying to reproduce the results and plot the figures in the paper and in the repository, two plotting scripts are referencing the directory `logs/figure6b`, for which, I only find the `logs/figure10`. I tried with `logs/figure10`, while the result seems different from the paper. Is it the case that the `logs/figure6b` directory should be re-generated from the testbed experiment? Thanks for your kind response.

**Comment by gudiandian** [comment]
Sorry for the late reply. Yes, the directory should be regenerated from testbed experiments.
